name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@944597f4a0709b9bc0446465693c7d9e1c15433d

    - name: Log in to Docker Hub
      uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514baad2da
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
      with:
        push: true
        tags: your-dockerhub-username/agi-pipeline:latest
