name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@1a44421d2379b183610001099a6792610738d8f2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack
